// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: proto/types/transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxSignReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   string                 `protobuf:"bytes,1,opt,name=FromAddress,json=from_address,proto3" json:"FromAddress,omitempty"`
	ToAddress     string                 `protobuf:"bytes,2,opt,name=ToAddress,json=to_address,proto3" json:"ToAddress,omitempty"`
	Value         uint64                 `protobuf:"varint,3,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSignReq) Reset() {
	*x = TxSignReq{}
	mi := &file_proto_types_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSignReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSignReq) ProtoMessage() {}

func (x *TxSignReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSignReq.ProtoReflect.Descriptor instead.
func (*TxSignReq) Descriptor() ([]byte, []int) {
	return file_proto_types_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TxSignReq) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TxSignReq) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TxSignReq) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TxSignReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TxSignRes struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedTransaction []byte                 `protobuf:"bytes,1,opt,name=SignedTransaction,json=transaction,proto3" json:"SignedTransaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TxSignRes) Reset() {
	*x = TxSignRes{}
	mi := &file_proto_types_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSignRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSignRes) ProtoMessage() {}

func (x *TxSignRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSignRes.ProtoReflect.Descriptor instead.
func (*TxSignRes) Descriptor() ([]byte, []int) {
	return file_proto_types_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TxSignRes) GetSignedTransaction() []byte {
	if x != nil {
		return x.SignedTransaction
	}
	return nil
}

type TxSendReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedTransaction []byte                 `protobuf:"bytes,1,opt,name=SignedTransaction,json=transaction,proto3" json:"SignedTransaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TxSendReq) Reset() {
	*x = TxSendReq{}
	mi := &file_proto_types_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSendReq) ProtoMessage() {}

func (x *TxSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSendReq.ProtoReflect.Descriptor instead.
func (*TxSendReq) Descriptor() ([]byte, []int) {
	return file_proto_types_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *TxSendReq) GetSignedTransaction() []byte {
	if x != nil {
		return x.SignedTransaction
	}
	return nil
}

type TxSendRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=Hash,json=hash,proto3" json:"Hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxSendRes) Reset() {
	*x = TxSendRes{}
	mi := &file_proto_types_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxSendRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxSendRes) ProtoMessage() {}

func (x *TxSendRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxSendRes.ProtoReflect.Descriptor instead.
func (*TxSendRes) Descriptor() ([]byte, []int) {
	return file_proto_types_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *TxSendRes) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type TxProveReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SignedTransaction []byte                 `protobuf:"bytes,1,opt,name=SignedTransaction,json=transaction,proto3" json:"SignedTransaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TxProveReq) Reset() {
	*x = TxProveReq{}
	mi := &file_proto_types_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxProveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxProveReq) ProtoMessage() {}

func (x *TxProveReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxProveReq.ProtoReflect.Descriptor instead.
func (*TxProveReq) Descriptor() ([]byte, []int) {
	return file_proto_types_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *TxProveReq) GetSignedTransaction() []byte {
	if x != nil {
		return x.SignedTransaction
	}
	return nil
}

type TxProveRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerkleProof   []byte                 `protobuf:"bytes,1,opt,name=MerkleProof,json=merkle_proof,proto3" json:"MerkleProof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxProveRes) Reset() {
	*x = TxProveRes{}
	mi := &file_proto_types_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxProveRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxProveRes) ProtoMessage() {}

func (x *TxProveRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxProveRes.ProtoReflect.Descriptor instead.
func (*TxProveRes) Descriptor() ([]byte, []int) {
	return file_proto_types_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *TxProveRes) GetMerkleProof() []byte {
	if x != nil {
		return x.MerkleProof
	}
	return nil
}

type TxVerifyReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TxHash               string                 `protobuf:"bytes,1,opt,name=TxHash,json=signed_transaction_hash,proto3" json:"TxHash,omitempty"`
	MerkleRootHash       string                 `protobuf:"bytes,2,opt,name=MerkleRootHash,json=merkle_root_hash,proto3" json:"MerkleRootHash,omitempty"`
	MerkleProofs         []string               `protobuf:"bytes,3,rep,name=MerkleProofs,json=merkle_proofs,proto3" json:"MerkleProofs,omitempty"`
	MerkleProofPositions []bool                 `protobuf:"varint,4,rep,packed,name=MerkleProofPositions,json=merkle_proofs_positions,proto3" json:"MerkleProofPositions,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TxVerifyReq) Reset() {
	*x = TxVerifyReq{}
	mi := &file_proto_types_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxVerifyReq) ProtoMessage() {}

func (x *TxVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxVerifyReq.ProtoReflect.Descriptor instead.
func (*TxVerifyReq) Descriptor() ([]byte, []int) {
	return file_proto_types_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *TxVerifyReq) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TxVerifyReq) GetMerkleRootHash() string {
	if x != nil {
		return x.MerkleRootHash
	}
	return ""
}

func (x *TxVerifyReq) GetMerkleProofs() []string {
	if x != nil {
		return x.MerkleProofs
	}
	return nil
}

func (x *TxVerifyReq) GetMerkleProofPositions() []bool {
	if x != nil {
		return x.MerkleProofPositions
	}
	return nil
}

type TxVerifyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=Valid,json=valid,proto3" json:"Valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxVerifyRes) Reset() {
	*x = TxVerifyRes{}
	mi := &file_proto_types_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxVerifyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxVerifyRes) ProtoMessage() {}

func (x *TxVerifyRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_types_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxVerifyRes.ProtoReflect.Descriptor instead.
func (*TxVerifyRes) Descriptor() ([]byte, []int) {
	return file_proto_types_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *TxVerifyRes) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_types_transaction_proto protoreflect.FileDescriptor

var file_proto_types_transaction_proto_rawDesc = string([]byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x22, 0x7f, 0x0a, 0x09, 0x54, 0x78, 0x53, 0x69, 0x67, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0b, 0x46, 0x72, 0x6f, 0x6d, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x09, 0x54, 0x6f, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x33, 0x0a, 0x09, 0x54, 0x78, 0x53, 0x69, 0x67,
	0x6e, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x33, 0x0a, 0x09,
	0x54, 0x78, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x26, 0x0a, 0x11, 0x53, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x1f, 0x0a, 0x09, 0x54, 0x78, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x48, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61,
	0x73, 0x68, 0x22, 0x34, 0x0a, 0x0a, 0x54, 0x78, 0x50, 0x72, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x26, 0x0a, 0x11, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f, 0x0a, 0x0a, 0x54, 0x78, 0x50, 0x72,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0b, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65,
	0x50, 0x72, 0x6f, 0x6f, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6d, 0x65, 0x72,
	0x6b, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x22, 0xbc, 0x01, 0x0a, 0x0b, 0x54, 0x78,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x12, 0x27, 0x0a, 0x06, 0x54, 0x78, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x73, 0x69, 0x67, 0x6e, 0x65,
	0x64, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x12, 0x28, 0x0a, 0x0e, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x52, 0x6f, 0x6f, 0x74,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x65, 0x72, 0x6b,
	0x6c, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x12, 0x23, 0x0a, 0x0c,
	0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0d, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66,
	0x73, 0x12, 0x35, 0x0a, 0x14, 0x4d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x6f, 0x66,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x08, 0x52,
	0x17, 0x6d, 0x65, 0x72, 0x6b, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x6f, 0x66, 0x73, 0x5f, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x23, 0x0a, 0x0b, 0x54, 0x78, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x0d, 0x5a,
	0x0b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_types_transaction_proto_rawDescOnce sync.Once
	file_proto_types_transaction_proto_rawDescData []byte
)

func file_proto_types_transaction_proto_rawDescGZIP() []byte {
	file_proto_types_transaction_proto_rawDescOnce.Do(func() {
		file_proto_types_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_types_transaction_proto_rawDesc), len(file_proto_types_transaction_proto_rawDesc)))
	})
	return file_proto_types_transaction_proto_rawDescData
}

var file_proto_types_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_types_transaction_proto_goTypes = []any{
	(*TxSignReq)(nil),   // 0: chain.TxSignReq
	(*TxSignRes)(nil),   // 1: chain.TxSignRes
	(*TxSendReq)(nil),   // 2: chain.TxSendReq
	(*TxSendRes)(nil),   // 3: chain.TxSendRes
	(*TxProveReq)(nil),  // 4: chain.TxProveReq
	(*TxProveRes)(nil),  // 5: chain.TxProveRes
	(*TxVerifyReq)(nil), // 6: chain.TxVerifyReq
	(*TxVerifyRes)(nil), // 7: chain.TxVerifyRes
}
var file_proto_types_transaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_types_transaction_proto_init() }
func file_proto_types_transaction_proto_init() {
	if File_proto_types_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_types_transaction_proto_rawDesc), len(file_proto_types_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_types_transaction_proto_goTypes,
		DependencyIndexes: file_proto_types_transaction_proto_depIdxs,
		MessageInfos:      file_proto_types_transaction_proto_msgTypes,
	}.Build()
	File_proto_types_transaction_proto = out.File
	file_proto_types_transaction_proto_goTypes = nil
	file_proto_types_transaction_proto_depIdxs = nil
}
