syntax = "proto3";
package chain;
option go_package = "protogen/pb";
import "proto/types/account.proto";
import "proto/types/accountBalance.proto";
import "proto/types/transaction.proto";
import "proto/types/block.proto";
import "proto/types/peers.proto";


service AccountService {
    rpc CreateAccount (CreateAccountReq) returns (CreateAccountResp);
    rpc AccountBalance (AccountBalanceReq) returns (AccountBalanceResp);
}

service TransactionService {
    rpc SignTransaction(TxSignReq) returns (TxSignRes);
    rpc SendTransaction(TxSendReq) returns (TxSendRes);
    rpc ProveTransaction(TxProveReq) returns(TxProveRes);
    rpc verifyTransaction(TxVerifyReq) returns(TxVerifyRes);
    rpc ReceiveTransaction(stream TxReceiveReq) returns (TxReceiveRes);
}

service BlockService {
    rpc SearchBlock(SearchBlockReq) returns(stream SearchBlockRes);
    rpc GenesisSync(GenesisSynReq) returns(GenesisSyncRes);
    rpc BlockSync(BlockSyncReq) returns (stream BlockSyncRes);
    rpc ReceiveBlock(stream BlockReceiveReq) returns(BlockReceiveRes);
}


service p2pService {
    rpc DiscoverPeers(PeerDiscoveryReq) returns(PeerDiscoveryResp);
}